### ISSUE TITLE
As a user of AGP I would like to be able to find a document by its popular title or abbreviation

### ISSUE THREAD

**Issue by NotoriousMBB** [laws-africa/peachjam#581] opened 2022-10-22 19:46 UTC
Some African Union documents are known and referenced using their acronyms or short titles, e.g. 
African Charter on Human and Peoples' Rights - Banjul Charter
Protocol  to  the  African  Charter  on  Human  and  Peoples’  Rights  on  the  Rights  of  Women in Africa, 2005 - Maputo Protocol (https://agp.africanlii.org/akn/aa-au/doc/general-comment/acerwc/2017/joint-general-comment-ending-child-marriage/eng@2017-10-01?q=maputo%20protocol)

Solemn Declaration on Gender Equality in Africa - SDGEA (https://agp.africanlii.org/akn/aa-au/statement/decision/au-assembly/2018/682/eng@2018-01-29?q=Declaration%20on%20Gender%20Equality%20in%20Africa)

**Comment by longhotsummer** [comment] 2022-10-31 07:10
Duplicate of https://github.com/laws-africa/peachjam/issues/616 which has a better write-up.

**Closed by longhotsummer** 2022-10-31 07:10 UTC
Labels: discovery
