### ISSUE TITLE
Add a Cause Lists menu item to TanzLII.

### ISSUE THREAD

**Issue by niiroobiro** [laws-africa/peachjam#1812] opened 2024-05-13 07:52 UTC
TanzLII wants us to add Cause Lists as a menu item

![Image](https://github.com/laws-africa/peachjam/assets/57619722/45e48337-32a7-408b-8d72-bcd67241a75b)

They will upload them as documents with titles and authors and then pull direct court names.

**Comment by longhotsummer** [comment] 2024-05-16 06:55
This is not a priority until the MVP (judgments, legislation and gazettes) is complete.

**Comment by actlikewill** [comment] 2024-05-27 15:48
@longhotsummer For this we said we are adding a new Causlist document model, with its own listing page and all other things that entails. Should we add an author field to it? Are there any other special fields?

**Comment by actlikewill** [comment] 2024-05-27 15:54
@longhotsummer Also would it be incorrect to have an frbr uri such as `/akn/tz/causelist/2002-02-03/1`? or does it need to be `/akn/tz/doc/causelist/2002-02-03/1`

**Comment by longhotsummer** [comment] 2024-05-28 07:58
They'll upload causeslists are generic documents and chose the causelist subtype, so we don't need a new model.

So the FRBR URI will be `/akn/tz/doc/causelist/...` -- there is no `causelist` in the AKN FRBR URI standard so we can't use it as the `frbr_doctype`.

**Comment by actlikewill** [comment] 2024-05-28 08:40
@longhotsummer I was to add a causelist model because it is also part of the KL requirements.

**Comment by actlikewill** [comment] 2024-05-28 11:10
@closed by #1830

**Closed by actlikewill** 2024-05-28 11:10 UTC
Labels: impact: medium
