### ISSUE TITLE
Editor cannot add a generic document to NamibLII

### ISSUE THREAD

**Issue by NotoriousMBB** [laws-africa/peachjam#1112] opened 2023-04-22 06:41 UTC
![image](https://user-images.githubusercontent.com/46931873/233767426-303195d8-aee6-4e2c-a2a5-1bbe326f306a.png)

![image](https://user-images.githubusercontent.com/46931873/233767471-662057f9-152b-4720-9286-b120d32893d4.png)

**Comment by NotoriousMBB** [comment] 2023-04-22 06:41
[https://media.namiblii.org/files/na/other/law-reform-report/NALRDC%2001/01%20LRDC%20-%20Report%20on%20the%20Aspects%20of%20Family%20Law.pdf](url)

Here is the file associated with the error above

**Comment by NotoriousMBB** [comment] 2023-04-22 06:43
Tried renaming the file to eliminate spaces and hyphens - still won't work

**Comment by NotoriousMBB** [comment] 2023-04-22 06:46
It looks like the system did not accept the file because I failed to specify a day in the date field (the document does not have a day it is just October 1994).  
So the issue is resolved, but a more specific error message would have helped.

**Comment by NotoriousMBB** [comment] 2023-04-22 06:47
@longhotsummer decide if you want to create a better error reporting ticket on this and close the issue. It is resolved for me for now.

**Comment by longhotsummer** [comment] 2023-04-24 06:45
The root cause here is the "day" part of the date field was not filled in. We should be validating that better on the server and marking it as required on the client.

**Closed** 2023-05-15 15:43 UTC
Labels: bug, impact: low
